name: Actions

on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build Unity project
    runs-on: ubuntu-latest
    steps:      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library
      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v2.0-alpha-2
        with:
          unityVersion: 2019.4.16f1

      - name: Build project
        uses: webbertakken/unity-builder@v2.0-alpha-6
        with:
          unityVersion: 2019.4.16f1
          targetPlatform: Linux
      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build