name: Actions

on: [pull_request, workflow_dispatch]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build Unity project
    runs-on: ubuntu-latest
    steps:      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2019.4.16f1
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2019.4.16f1
          allowDirtyBuild: true
          targetPlatform: Android
      # Output build artifact
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
      # Output test results
      - uses: actions/upload-artifact@v2
        with:
         name: Test results
         path: artifacts
